CREATE DATABASE CRUD;
USE CRUD;

CREATE TABLE PERSONA{
 	ID_P INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
 	DNI CHAR(8);
 	NOMBRE_P VARCHAR(25) NOT NULL;
 	PATERNO_P VARCHAR(15) NOT NULL;
 	MATERNO_P VARCHAR(15) NOT NULL;
 	FECHA_NAC_P DATE NOT NULL;
 	TELEFONO_P VARCHAR(15) NOT NULL;
 	DIRECCION_P VARCHAR(35) NOT NULL;
 	ESTADO_CIVIL_P VARCHAR(15)
};